/* Regression walk (Prompt 15): docs/QA-CHECKLIST.md run in Playwright against
 * the audit fixtures, phone first (390) and desktop (1280). Every step is one
 * action and one expectation; a failed step is recorded and the walk goes on.
 * Writes answer ok through the mocks, so the optimistic UI is what is checked.
 *
 *   npx vite build && npx vite preview --port 4330 &
 *   node scripts/regression.mjs
 *   AUDIT_WIDTHS=390 node scripts/regression.mjs
 */
import { spawnSync } from 'node:child_process';
import { chromium } from 'playwright-core';
import { mockRoutes } from './audit-fixtures.mjs';

const EXE = process.env.PW_CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const BASE = process.env.AUDIT_BASE || 'http://127.0.0.1:4330';
const WIDTHS = process.env.AUDIT_WIDTHS ? process.env.AUDIT_WIDTHS.split(',').map(Number) : [390, 1280];
const T = 6000;

const browser = await chromium.launch({ executablePath: EXE, args: ['--no-sandbox'] });
const results = [];
let failures = 0;
/* Step 0 (CRM revamp, step 6): ESLint first, so a missing import (the
   kind of crash the fixtures never reach) fails the audit before the walk. */
{
  const r = spawnSync('npx', ['eslint', 'src', 'api', 'scripts'], { encoding: 'utf8' });
  const out = `${r.stdout || ''}${r.stderr || ''}`;
  const errors = (out.match(/(\d+) errors?/) || [])[1];
  const ok = r.status === 0;
  if (!ok) { failures++; console.log(out.split('\n').filter(l => /error/.test(l)).slice(0, 40).join('\n')); }
  for (const width of [390, 1280]) results.push({ width, n: 0, name: 'ESLint: no undefined identifier, no unused import', ok, note: ok ? 'clean' : `${errors || '?'} errors` });
  console.log(`  ${ok ? 'ok  ' : 'FAIL'} 0. ESLint: no undefined identifier, no unused import${ok ? '' : ` (${errors || '?'} errors)`}`);
}

for (const width of WIDTHS) {
  const phone = width < 768;
  const ctx = await browser.newContext({ viewport: { width, height: 844 }, hasTouch: phone, serviceWorkers: 'block' });
  const page = await ctx.newPage();
  await page.addInitScript(() => { try { localStorage.clear(); localStorage.setItem('vz_boot', '1'); localStorage.setItem('vz_theme', 'dark'); } catch {} });
  let signedIn = true;
  await page.route('**/api/admin/session', r => r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ authed: signedIn }) }));
  await mockRoutes(page);
  await page.route('**/api/admin/logout', r => { signedIn = false; return r.fulfill({ status: 200, contentType: 'application/json', body: '{"ok":true}' }); });
  await page.route('**/api/admin/login', r => { signedIn = true; return r.fulfill({ status: 200, contentType: 'application/json', body: '{"ok":true}' }); });
  const goto = (p) => page.goto(BASE + p, { waitUntil: 'domcontentloaded', timeout: 15000 });
  // Data lands after the 150ms skeleton delay: wait for the region to hold something, then for the skeleton to leave.
  const settle = async () => { await page.waitForFunction(() => { const c = document.querySelector('.sh-content'); return c && (c.querySelector('.v-skel, .v-card, .lc, .v-lrow, .v-empty, .v-error, .v-tr')); }, null, { timeout: 8000 }).catch(() => {}); await page.waitForFunction(() => !document.querySelector('.sh-content .v-skel'), null, { timeout: 8000 }).catch(() => {}); await page.waitForTimeout(250); };
  const dialog = () => page.locator('[role="dialog"]').last();
  const esc = async () => { await page.keyboard.press('Escape'); await page.waitForTimeout(350); };
  const toastText = async () => page.locator('.v-toast').last().textContent({ timeout: 3000 }).catch(() => '');
  const expectVisible = async (loc, what) => { await loc.first().waitFor({ state: 'visible', timeout: T }); return what; };

  const step = async (n, name, fn) => {
    try { const note = await fn(); results.push({ width, n, name, ok: true, note: note || '' }); console.log(`  ok   [${width}] ${n}. ${name}${note ? `: ${note}` : ''}`); }
    catch (e) { failures++; results.push({ width, n, name, ok: false, note: String(e.message || e).split('\n')[0].slice(0, 140) }); console.log(`  FAIL [${width}] ${n}. ${name}: ${String(e.message || e).split('\n')[0].slice(0, 160)}`); }
  };
  const openLeadCard = async (name) => { await page.getByRole('button', { name: `Open ${name}` }).first().click({ timeout: T }); await page.waitForTimeout(500); };
  const tab = (name) => page.getByRole('tab', { name: new RegExp('^' + name) }).first().click({ timeout: T });

  console.log(`\nRegression walk at ${width}px`);
  await step(1, 'Open the app', async () => { await goto('/admin'); await expectVisible(page.locator('.sh-root'), ''); return 'shell up'; });
  await step(2, 'Next up greets Rob', async () => { await settle(); await expectVisible(page.locator('.db-greet'), ''); const t = await page.locator('.db-greet').textContent(); if (!/Good (morning|afternoon|evening), Rob/.test(t)) throw new Error(`greeting was "${t}"`); return t.trim(); });
  await step(3, 'Next up is filled', async () => { await expectVisible(page.locator('.nu-row, .db-panel .v-empty, .db-next .v-empty'), ''); const rows = await page.locator('.nu-row').count(); await page.getByRole('button', { name: /^Stats/ }).first().click({ timeout: T }); await page.waitForTimeout(500); await expectVisible(page.locator('.db-funnel .db-step'), ''); const n = await page.locator('.v-stat').count(); if (n < 4) throw new Error(`${n} stat cards`); return `${rows} next up rows, ${n} stats`; });
  /* CRM revamp, step 6: the lead card's row menu on Leads, Lists and the Call tab renders without an ErrorBoundary (the production crash was a missing import in leadMenuItems). */
  const noBoundary = async () => { const n = await page.locator('.v-boundary').count(); if (n) throw new Error('an ErrorBoundary rendered'); };
  await step('3a', 'A lead card row menu opens on Leads and Lists without a crash', async () => {
    await page.evaluate(() => localStorage.setItem('vz_leads_view', JSON.stringify('list')));
    await goto('/admin/leads'); await settle();
    await page.getByRole('button', { name: /^Actions for Lead Business/ }).first().click({ timeout: T }); await page.waitForTimeout(300);
    const items = await page.getByRole('menuitem').count(); if (!items) throw new Error('no menu items on Leads'); await noBoundary(); await esc();
    await goto('/admin/lists'); await settle(); await page.getByRole('button', { name: /^Open Tuesday morning/ }).click({ timeout: T }); await settle();
    const rowMenu = page.locator('.ls-item').first().getByRole('button', { name: /actions|Remove|More/i }).first();
    if (await rowMenu.count()) { await rowMenu.click({ timeout: T }); await page.waitForTimeout(300); await noBoundary(); await esc(); }
    await goto('/admin'); await settle();
    return `${items} items on Leads, Lists rows open`;
  });
  await step(4, 'Start call session opens the lists, Quick session opens the builder', async () => { await page.getByRole('button', { name: 'Start call session' }).first().click({ timeout: T }); await expectVisible(page.locator('.ls-card, .cc-quick'), ''); const cards = await page.locator('.ls-card').count(); await page.getByRole('button', { name: 'Quick session' }).first().click({ timeout: T }); await expectVisible(page.locator('.cc-start'), ''); return `${cards} lists, then ${(await page.locator('.cc-start').textContent()).trim()}`; });
  await step(5, 'Start in the builder opens the queue or room', async () => { await page.locator('.cc-start').click({ timeout: T }); await page.waitForTimeout(600); const room = await page.locator('.cc-head').count(); const queue = await page.locator('.cc-qlist .lc').count(); if (!room && !queue) throw new Error('neither queue nor room'); return room ? 'room' : `queue with ${queue} leads`; });
  await step(6, 'The room shows the first lead', async () => { if (!(await page.locator('.cc-head').count())) { await page.locator('.cc-qlist .lc-open').first().click({ timeout: T }); } await expectVisible(page.locator('.cc-head .cc-biz'), ''); return (await page.locator('.cc-pos').first().textContent().catch(() => '')).trim(); });
  // The undo toast sits over the outcome bar on a phone for six seconds; dismiss it the way a thumb would before the next outcome.
  const dismissToasts = async () => { for (const x of await page.locator('.v-toast-x').all()) await x.click({ timeout: 1000 }).catch(() => {}); await page.waitForTimeout(250); };
  const outcome = async (label, action) => { await dismissToasts(); await page.locator('.cc-outs button', { hasText: label }).first().click({ timeout: T }); await expectVisible(dialog(), ''); if (action) await action(); await dialog().getByRole('button', { name: /^(Log|Set callback|Book it)$/ }).click({ timeout: T }); await page.waitForFunction(() => !document.querySelector('[role="dialog"]'), null, { timeout: T }); await page.waitForTimeout(400); return (await page.locator('.cc-pos').first().textContent().catch(() => '')).trim(); };
  await step('6a', 'The call room lead menu opens without a crash', async () => { await page.getByRole('button', { name: 'Lead actions' }).first().click({ timeout: T }); await page.waitForTimeout(300); const items = await page.getByRole('menuitem').count(); if (!items) throw new Error('no menu items'); await noBoundary(); await esc(); return `${items} items`; });
  await step(7, 'Log No answer', async () => `position ${await outcome('No answer')}`);
  await step(8, 'Log Callback with a quick time', async () => `position ${await outcome('Callback', async () => { await dialog().locator('.v-chip').first().click({ timeout: T }); })}`);
  await step(9, 'Log Wrong number', async () => `position ${await outcome('Wrong number')}`);
  await step(10, 'Book a meeting', async () => { const pos = await outcome('Booked', async () => { const d = new Date(); d.setDate(d.getDate() + 2); await dialog().locator('input[type="date"]').fill(d.toISOString().slice(0, 10)); await dialog().locator('input[type="time"]').fill('10:00'); }); return `position ${pos}`; });
  await step(11, 'Log Said no on the last lead', async () => { await dismissToasts(); await page.locator('.cc-outs button', { hasText: 'Said no' }).first().click({ timeout: T }); await expectVisible(dialog(), ''); await dialog().getByRole('button', { name: 'Log' }).click({ timeout: T }); await page.waitForTimeout(400); const t = await toastText(); if (!/Undo/i.test(t)) throw new Error(`no undo toast: "${t}"`); await page.waitForTimeout(900); const summary = await page.locator('.cc-summary').count(); return `undo toast${summary ? ', session summary' : ''}`; });
  await step('11a', 'Triage shows the pile and Keep moves the top lead to Leads', async () => { await goto('/admin/triage'); await settle(); const stack = await page.locator('.tr-deck .tr-card').count(); const rows = await page.locator('.tr-shell .v-tr').count(); if (!stack && !rows) throw new Error('no pile'); if (phone) await page.getByRole('button', { name: /^Keep Lead Business 16/ }).click({ timeout: T }); else { await page.getByRole('button', { name: /^Lead Business 16 actions$/ }).click({ timeout: T }); await page.getByRole('menuitem', { name: 'Keep' }).click({ timeout: T }); } await expectVisible(dialog(), ''); await dialog().getByRole('radio', { name: 'Hot' }).click({ timeout: T }); await dialog().getByRole('button', { name: 'Done' }).click({ timeout: T }); await page.waitForTimeout(600); const t = await toastText(); if (!/kept/i.test(t)) throw new Error(`toast "${t}"`); return `${stack ? `${stack} cards` : `${rows} rows`}, ${t.replace(/\s+/g, ' ').slice(0, 40)}`; });
  await step('11b', 'Capture a lead from Quick add', async () => { await dismissToasts(); await page.getByRole('button', { name: 'Quick add' }).click({ timeout: T }); await page.getByRole('menuitem', { name: 'Capture a lead' }).click({ timeout: T }); await expectVisible(dialog(), ''); await dialog().getByLabel('Handle, phone or business').fill('@thebakeryco'); await dialog().getByRole('button', { name: 'Capture' }).click({ timeout: T }); await page.waitForTimeout(600); const t = await toastText(); if (!/Captured/.test(t)) throw new Error(`toast "${t}"`); return t.trim(); });
  await step('12a', 'Lists shows the open lists and opens one', async () => { await goto('/admin/lists'); await settle(); const n = await page.locator('.ls-card').count(); if (n < 2) throw new Error(`${n} list cards`); await page.getByRole('button', { name: /^Open Tuesday morning/ }).click({ timeout: T }); await settle(); const rows = await page.locator('.ls-item').count(); if (!rows) throw new Error('no leads on the list'); return `${n} lists, ${rows} leads on the first`; });
  await step(12, 'Deals shows the board or the grouped list', async () => { await goto('/admin/deals'); await settle(); const n = await page.locator('.dl-card').count(); if (!n) throw new Error('no deal cards'); const cols = await page.locator('.dl-col').count(); return cols ? `${n} cards in ${cols} columns` : `${n} cards, grouped`; });
  await step(13, 'Open the booked lead', async () => { await page.getByRole('button', { name: /^Open Lead Business 8/ }).first().click({ timeout: T }); await expectVisible(page.locator('.dt-profile'), ''); return 'detail open'; });
  await step(14, 'Add two pricing options', async () => { await tab('Meeting'); await page.waitForTimeout(400); await page.locator('.dt-addopt').first().click({ timeout: T }); await page.locator('.dt-addopt').first().click({ timeout: T }); await page.waitForTimeout(400); const n = await page.locator('.dt-opt').count(); if (n < 2) throw new Error(`${n} options`); return `${n} options`; });
  await step('14a', 'Send the intro email from the Checkpoints fold', async () => { await tab('Checkpoints'); await page.waitForTimeout(400); await page.locator('.dc-send').first().scrollIntoViewIfNeeded().catch(() => {}); await page.locator('.dc-send').first().click({ timeout: T }); await expectVisible(dialog(), ''); await dialog().locator('.se-send').click({ timeout: T }); await page.waitForTimeout(600); const t = await toastText(); if (!/Intro email sent to/.test(t)) throw new Error(`toast "${t}"`); await dismissToasts(); return t.trim().slice(0, 60); });
  await step(15, 'Met them, then Mark paid on the first invoice makes the client and the project', async () => { await tab('Checkpoints'); await page.waitForTimeout(400); await page.locator('.dc-met').first().scrollIntoViewIfNeeded().catch(() => {}); await page.locator('.dc-met').first().click({ timeout: T }); await page.waitForTimeout(500); await dismissToasts(); await page.locator('.iv-add').first().click({ timeout: T }); await expectVisible(dialog(), ''); await dialog().getByRole('button', { name: 'Add', exact: true }).click({ timeout: T }); await page.waitForTimeout(500); await dismissToasts(); await page.getByRole('button', { name: /actions$/ }).filter({ hasText: '' }).last().click({ timeout: T }); await page.getByRole('menuitem', { name: 'Mark paid' }).click({ timeout: T }); await expectVisible(dialog(), ''); await dialog().locator('.iv-pay-confirm').click({ timeout: T }); await page.waitForTimeout(400); await page.getByRole('dialog').last().getByRole('button', { name: 'Mark paid' }).click({ timeout: T }); await page.waitForTimeout(1200); const t = await toastText(); if (!/client/i.test(t)) throw new Error(`toast "${t}"`); return t.replace(/\s+/g, ' ').slice(0, 60); });
  await step(16, 'Open a client', async () => { await goto('/admin/clients'); await settle(); if (phone) await openLeadCard('Lead Business 11'); else await page.locator('.v-tr', { hasText: 'Lead Business 11' }).first().click({ timeout: T }); await expectVisible(page.getByRole('tab', { name: /^Projects/ }), ''); return 'client detail with tabs'; });
  await step(17, 'Create a project (a phone gets the computer-only card)', async () => { await tab('Projects'); await page.locator('.cw-new-project').first().click({ timeout: T }); await expectVisible(dialog(), ''); if (phone) { await expectVisible(dialog().locator('.co-card'), ''); await esc(); return 'computer-only card'; } await dialog().locator('.v-sheet-foot .v-btn, .v-modal-foot .v-btn').last().click({ timeout: T }); await page.waitForFunction(() => !document.querySelector('[role="dialog"]'), null, { timeout: T }); await page.waitForTimeout(400); return 'sheet closed, project created'; });
  await step(18, 'Mark an invoice paid', async () => { await tab('Payments'); await page.waitForTimeout(400); await page.locator('.iv-paid').first().scrollIntoViewIfNeeded().catch(() => {}); await page.locator('.iv-paid').first().click({ timeout: T }); await expectVisible(dialog(), ''); await dialog().locator('.iv-pay-confirm').click({ timeout: T }); await page.waitForTimeout(800); const t = await toastText(); if (!/recorded/i.test(t)) throw new Error(`toast "${t}"`); return t.replace(/\s+/g, ' ').slice(0, 60); });
  await step(19, 'Start a retainer (a phone gets the computer-only card)', async () => { await tab('Retainer'); await page.locator('.cw-start-retainer').first().click({ timeout: T }); await expectVisible(dialog(), ''); if (phone) { await expectVisible(dialog().locator('.co-card'), ''); await esc(); return 'computer-only card'; } await dialog().getByRole('button', { name: 'Create' }).click({ timeout: T }); await page.waitForFunction(() => !document.querySelector('[role="dialog"]'), null, { timeout: T }); await page.waitForTimeout(600); return 'retainer created'; });
  await step(20, 'Log a delivery on a retainer client', async () => { await goto('/admin/clients'); await settle(); if (phone) await openLeadCard('Lead Business 12'); else await page.locator('.v-tr', { hasText: 'Lead Business 12' }).first().click({ timeout: T }); await tab('Retainer'); await page.locator('.cw-log-delivery').first().click({ timeout: T }); await expectVisible(dialog(), ''); const num = dialog().locator('input[type="number"]').first(); if (await num.count()) await num.fill('2'); await dialog().getByRole('button', { name: 'Log' }).click({ timeout: T }); await page.waitForFunction(() => !document.querySelector('[role="dialog"]'), null, { timeout: T }); return 'delivery logged'; });
  await step(21, 'New order sheet opens', async () => { await goto('/admin/orders'); await settle(); await page.getByRole('button', { name: /^New order/ }).first().click({ timeout: T }); await expectVisible(dialog(), ''); return 'sheet open'; });
  await step(22, 'Create an order with one item', async () => { await dialog().getByLabel('Name').first().fill('Walk In Customer'); await dialog().getByRole('button', { name: 'Add item' }).click({ timeout: T }); await page.waitForTimeout(300); await dialog().getByRole('button', { name: 'Create order' }).click({ timeout: T }); await page.waitForTimeout(800); const t = await toastText(); if (!/created/i.test(t)) throw new Error(`toast "${t}"`); await esc(); return t.trim(); });
  await step(23, 'Mark an order paid', async () => { await goto('/admin/orders'); await settle(); if (phone) await page.getByRole('button', { name: /^Open order for Person 0/ }).first().click({ timeout: T }); else await page.locator('.v-tr', { hasText: 'Person 0' }).first().click({ timeout: T }); await page.getByRole('button', { name: /^Mark paid/ }).first().click({ timeout: T }); await expectVisible(dialog(), ''); await dialog().locator('.v-modal-foot .v-btn').last().click({ timeout: T }); await page.waitForTimeout(800); const paid = await page.getByText(/^Paid \$/).count(); if (!paid) throw new Error('no paid line'); return 'paid line shown'; });
  await step('23a', 'Projects lists every project with its next action and next invoice', async () => { await goto('/admin/projects'); await settle(); const n = phone ? await page.locator('.pj-card').count() : await page.locator('.pj-shell .v-tr').count(); if (!n) throw new Error('no projects'); const strip = (await page.locator('.pj-strip').textContent()).trim(); if (!/open, .* due this week, .* past due/.test(strip)) throw new Error(`strip "${strip}"`); if (phone) await page.getByRole('button', { name: /^Open Lead Business 11/ }).first().click({ timeout: T }); else await page.locator('.pj-shell .v-tr', { hasText: 'Lead Business 11' }).first().click({ timeout: T }); await expectVisible(page.locator('.dt-profile'), ''); return `${n} projects, ${strip}`; });
  await step(24, 'Concepts list opens a set in the editor (a phone gets the computer-only card)', async () => { await goto('/admin/concepts'); await settle(); await page.getByRole('button', { name: /^Open Lead Business 8/ }).first().click({ timeout: T }); await settle(); if (phone) { await expectVisible(page.locator('.co-card'), ''); await page.getByRole('button', { name: 'Copy link' }).click({ timeout: T }); await page.waitForTimeout(400); const t = await toastText(); if (!/copied/i.test(t)) throw new Error(`toast "${t}"`); return 'computer-only card, link copied'; } await expectVisible(page.locator('.ce-dir').first(), ''); const n = await page.locator('.ce-dir').count(); return `${n} directions in the editor`; });
  await step(25, 'Edit a concept set and save it (computer only)', async () => { if (phone) return 'skipped on a phone, the editor is computer only'; await page.getByLabel('Title').first().fill('Regression title'); await page.getByLabel('Title').first().blur(); await page.waitForTimeout(400); await page.getByRole('button', { name: 'Save changes' }).click({ timeout: T }); await page.waitForTimeout(800); const t = await toastText(); if (!/saved/i.test(t)) throw new Error(`toast "${t}"`); return t.trim(); });
  await step('25a', 'The phone tab bar and More sheet', async () => { if (!phone) return 'desktop, no tab bar'; await goto('/admin'); await settle(); const tabs = (await page.locator('.sh-tab .sh-tab-label').allTextContents()).map(t => t.trim()); if (tabs.join(',') !== 'Next up,Lists,Call,Deals,More') throw new Error(`tabs ${tabs.join(',')}`); await page.locator('.sh-tab--more').click({ timeout: T }); await expectVisible(dialog(), ''); const rows = (await dialog().locator('.sh-more-label').allTextContents()).map(t => t.trim()); const note = await dialog().locator('.sh-more-computer').count(); await esc(); if (rows.join(',') !== 'Triage,Leads,Clients,Projects,Orders,Reviews,Calendar,Submissions,Recently Deleted,Concepts,Declined,Settings' || !note) throw new Error(`more ${rows.join(',')} note ${note}`); return `${tabs.length} tabs, ${rows.length} rows, computer note`; });
  await step(26, 'Log a review ask', async () => { await goto('/admin/reviews'); await settle(); await page.getByRole('button', { name: /^Open reviews for Lead Business 12/ }).first().click({ timeout: T }); await page.locator('.rv-log-ask').first().click({ timeout: T }); await page.waitForTimeout(800); const t = await toastText(); if (!/ask|logged/i.test(t)) throw new Error(`toast "${t}"`); return t.replace(/\s+/g, ' ').slice(0, 50); });
  await step(27, 'Calendar shows today', async () => { await goto('/admin/calendar'); await page.evaluate(() => localStorage.setItem('vz_cal_view', JSON.stringify('day'))); await goto('/admin/calendar'); await settle(); await expectVisible(page.locator('.cal-strip, .cal-week'), ''); const day = await page.locator('.cal-strip').count(); const n = await page.locator(day ? '.cal-row' : '.cal-block').count(); return day ? `${n} events today` : `week view, ${n} blocks`; });
  await step(28, 'Notifications drawer opens', async () => { await page.locator('.sh-bell').first().click({ timeout: T }); await expectVisible(dialog(), ''); const n = await page.locator('.sh-notif').count(); await esc(); return `${n} items`; });
  await step(29, 'Theme switches to Light and back', async () => { await goto('/admin/settings'); await settle(); await page.getByRole('radio', { name: 'Light' }).click({ timeout: T }); await page.waitForTimeout(300); const light = await page.evaluate(() => document.documentElement.dataset.vTheme); if (light !== 'light') throw new Error(`theme is ${light}`); await page.getByRole('radio', { name: 'Dark' }).click({ timeout: T }); await page.waitForTimeout(300); return 'light then dark'; });
  await step(30, 'Reduce motion on and off', async () => { const sw = page.getByRole('switch', { name: 'Reduce motion' }); await sw.click({ timeout: T }); await page.waitForTimeout(300); const on = await page.evaluate(() => document.documentElement.dataset.vMotion); if (on !== 'reduce') throw new Error('data-v-motion not set'); await sw.click({ timeout: T }); await page.waitForTimeout(300); const off = await page.evaluate(() => document.documentElement.dataset.vMotion); if (off) throw new Error('still reduced'); return 'reduce then normal'; });
  await step(31, 'Sign out', async () => { if (phone) { await page.locator('.sh-tab--more').click({ timeout: T }); await dialog().getByRole('button', { name: 'Sign out' }).click({ timeout: T }); } else { await page.locator('.sh-top-avatarbtn').click({ timeout: T }); await page.getByRole('menuitem', { name: 'Sign out' }).click({ timeout: T }); } await expectVisible(page.locator('.aa-login'), ''); return 'login card'; });
  await step(32, 'Sign back in', async () => { await page.getByLabel('Password').fill('correct horse'); await page.waitForTimeout(200); await page.getByRole('button', { name: 'Sign in' }).click({ timeout: T }); await page.waitForTimeout(500); await expectVisible(page.locator('.sh-root'), ''); await goto('/admin'); await settle(); await expectVisible(page.locator('.db-greet'), ''); const theme = await page.evaluate(() => document.documentElement.dataset.vTheme); return `dashboard back, theme ${theme}`; });
  await ctx.close();
}
await browser.close();

let md = `\n| # | Step | 390 | 1280 |\n|---|---|---|---|\n`;
const steps = [...new Set(results.map(r => r.n))];
for (const n of steps) { const a = results.find(r => r.n === n && r.width === 390); const b = results.find(r => r.n === n && r.width === 1280); const cell = (r) => (r ? (r.ok ? `ok${r.note ? ` (${r.note})` : ''}` : `FAIL: ${r.note}`) : 'n/a'); md += `| ${n} | ${(a || b).name} | ${cell(a)} | ${cell(b)} |\n`; }
md += `\nSteps: ${results.length}. Failures: ${failures}.\n`;
console.log(md.replace(/\|/g, '|'));
process.exit(failures ? 1 : 0);
